# This service simply exposes a way to load balance across
# pods that match the selector (label model-name: salary-predictor)
# over the specified port
#
# For this to work outside the cluster, an ingress service
# is also required to be created OR a service of type NodePort
apiVersion: v1
kind: Service
metadata:
  name: salary-predictor-service
spec:
  selector:
    app: salary-predictor
  ports:
    - protocol: TCP
      port: 9000
      name: http
      targetPort: 9000